/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorCadastroPossuirBolsas;
import entidade.Item;
import entidade.Bolsa;
import entidade.Possuir;
import javax.swing.DefaultComboBoxModel;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class JanelaCadastrarPossuir extends javax.swing.JFrame {

    ControladorCadastroPossuirBolsas controlador;
    JanelaCadastrarBolsas janela_mãe;
    int sequencial_bolsa;
    Item[] itens_cadastrados;
    DefaultListModel itens_lista_possuir;
    
    
    public JanelaCadastrarPossuir(ControladorCadastroPossuirBolsas controlador,
            JanelaCadastrarBolsas janela_mãe, int sequencial_bolsa) {
  
        this.controlador = controlador;
        this.janela_mãe = janela_mãe;
        this.sequencial_bolsa = sequencial_bolsa;
        itens_cadastrados = Item.getVisões();
        initComponents();
        atualizarPesoBolsa();
        atualizarListaPossuirBolsas();
    }

    private void atualizarPesoBolsa() {
        Bolsa bolsa = Bolsa.buscarBolsa(sequencial_bolsa);
        bolsaLabel.setText("Bolsa: " + bolsa.getPesoMax());

    }
    
    
     private void atualizarListaPossuirBolsas() {
        itens_lista_possuir = (DefaultListModel) itens_bolsasList.getModel();
        Possuir[] possuir_bolsa = Possuir.buscarPossuirBolsa(sequencial_bolsa);
        for (Possuir possuir : possuir_bolsa) {
            itens_lista_possuir.addElement(possuir);
        }
    }   
     
      private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void informarSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itens_cadastradosComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        InserirButtom = new javax.swing.JButton();
        removerButtom = new javax.swing.JButton();
        itens_bolsaScrollPane = new javax.swing.JScrollPane();
        itens_bolsasList = new javax.swing.JList();
        bolsaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Possuir");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizarJanelaCadastroPossuir(evt);
            }
        });

        jLabel1.setText("Itens cadastrados:");

        jLabel2.setText("Itens na bolsa");

        itens_cadastradosComboBox.setModel(new DefaultComboBoxModel(itens_cadastrados));
        itens_cadastradosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        InserirButtom.setText("Inserir");
        InserirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirPossuir(evt);
            }
        });

        removerButtom.setText("Remover");
        removerButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPossuir(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InserirButtom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removerButtom)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InserirButtom)
                    .addComponent(removerButtom))
                .addContainerGap())
        );

        itens_bolsasList.setModel(new DefaultListModel());
        itens_bolsasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itens_bolsaScrollPane.setViewportView(itens_bolsasList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(itens_cadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itens_bolsaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bolsaLabel)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bolsaLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itens_cadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(itens_bolsaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirPossuir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirPossuir
        Item visão_item = (Item) itens_cadastradosComboBox.getSelectedItem();
        String mensagem_erro = null;
        Possuir possuir = null;
        if (visão_item != null) {
            Bolsa visão_bolsa = Bolsa.buscarBolsa(sequencial_bolsa);
            possuir = new Possuir(0, visão_bolsa, visão_item);
            mensagem_erro = controlador.inserirPossuir(possuir);
            if (mensagem_erro == null) {
                int sequencial = Possuir.últimoSequencial();
                possuir.setSequencial(sequencial);
                itens_lista_possuir.addElement(possuir);
            } else {
                informarErro(mensagem_erro);
            }
        }
    }//GEN-LAST:event_InserirPossuir

    private void removerPossuir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPossuir
        Possuir visão = (Possuir) itens_bolsasList.getSelectedValue();
        if (visão != null) {
            int sequencial = visão.getSequencial();
            String mensagem_erro = controlador.removerPossuir(sequencial);
            if (mensagem_erro == null) {
                itens_lista_possuir.removeElement(visão);
            } else {
                informarErro(mensagem_erro);
            }
        } else {
            informarErro("Nenhum Item foi selecionado");
        }
    }//GEN-LAST:event_removerPossuir

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void atualizarJanelaCadastroPossuir(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_atualizarJanelaCadastroPossuir
         janela_mãe.atualizarListaPossuirBolsas(sequencial_bolsa);
    }//GEN-LAST:event_atualizarJanelaCadastroPossuir

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InserirButtom;
    private javax.swing.JLabel bolsaLabel;
    private javax.swing.JScrollPane itens_bolsaScrollPane;
    private javax.swing.JList itens_bolsasList;
    private javax.swing.JComboBox itens_cadastradosComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removerButtom;
    // End of variables declaration//GEN-END:variables
}
